# Generated by Django 3.1.3 on 2020-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20201126_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
